cc_library(
    name = "internal",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//puddle/cli:__pkg__"],
    deps = [
        "//puddle/log",
        "@abseil-cpp//absl/strings",
    ],
)
