cc_library(
    name = "reactor",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
    deps = [
        "//puddle/log",
        "//puddle/shard",
        "@fmt",
    ],
)
