cc_library(
    name = "cli",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
    deps = [
        "//puddle/cli/internal",
        "@abseil-cpp//absl/strings",
    ],
)
