cc_library(
    name = "net",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
    deps = [
        "//puddle/reactor",
        "@abseil-cpp//absl/types:span",
    ],
)
